spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://167.179.64.235:3306/message_app?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mtfan#123
    druid:
      initial-size: 5
      max-active: 20
      web-stat-filter:
        enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 167.179.64.235
    port: 6379
    password: mtfan#123
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
    jedis:
      pool:
        max-idle: 50
        min-idle: 1
        max-wait: -1
        max-active: -1
  redisson:
    address: redis://167.179.64.235:6379
    password: mtfan#123
    thread: 4
    codec: org.redisson.codec.JsonJacksonCodec
    connectionMinimumIdleSize: 2
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    #执行失败最大次数, 默认值：3；失败后直到 reconnectionTimeout超时以后再次尝试。
    retryAttempts: 2
    #连接池最大容量。默认值：64；连接池的连接数量自动弹性伸缩
    connectionPoolSize: 3
    #数据库编号，默认值：0
    database: 0

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

server:
  port: 8080
  servlet:
    context-path: /eva-app
